// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsqGzLz5zPKcME6rtbQoQoVANkU2RAHnw',
    appId: '1:62880191670:web:e2ac9078c58b1a1a3ec217',
    messagingSenderId: '62880191670',
    projectId: 'my-bloc-photo-app',
    authDomain: 'my-bloc-photo-app.firebaseapp.com',
    storageBucket: 'my-bloc-photo-app.appspot.com',
    measurementId: 'G-8K5DCB1VY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ_h-PTbai-ZD_XD59sWZTg-xflTHsG0o',
    appId: '1:62880191670:android:6e22e926d553e5b93ec217',
    messagingSenderId: '62880191670',
    projectId: 'my-bloc-photo-app',
    storageBucket: 'my-bloc-photo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS3jrKV1xh4tNkSVcBdRTJN4Q7Dw4VF3M',
    appId: '1:62880191670:ios:c165c5f72140d1303ec217',
    messagingSenderId: '62880191670',
    projectId: 'my-bloc-photo-app',
    storageBucket: 'my-bloc-photo-app.appspot.com',
    iosClientId:
        '62880191670-68g0pvjgclrj23cvt6n8tml4oaoqmslq.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocCourseWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS3jrKV1xh4tNkSVcBdRTJN4Q7Dw4VF3M',
    appId: '1:62880191670:ios:c165c5f72140d1303ec217',
    messagingSenderId: '62880191670',
    projectId: 'my-bloc-photo-app',
    storageBucket: 'my-bloc-photo-app.appspot.com',
    iosClientId:
        '62880191670-68g0pvjgclrj23cvt6n8tml4oaoqmslq.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocCourseWithFirebase',
  );
}
